In [1]:
import numpy as np

In [2]:
# NumPy is a Python library that provides fast and efficient array operations and functions for data science.
my_arr=np.arange(1000000)

my_list = list(range(1000000))

In [3]:
# NumPy-based algorithms are generally 10 to 100 times faster (or more) 
# than their pure Python counterparts and use significantly less memory.

print("numpy excution time")
%timeit my_arr2=my_arr*2

print("list excution time")
%timeit mylist2=[x*2 for x in my_list]

numpy excution time
3.19 ms ± 541 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
list excution time
113 ms ± 6.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
data=np.array([[1.5,-0.5,3],[0,-3,6.5]])
print(data)

#some mathematical operation on data
print("multiply with 3 \n",data*3)


[[ 1.5 -0.5  3. ]
 [ 0.  -3.   6.5]]
multiply with 3 
 [[ 4.5 -1.5  9. ]
 [ 0.  -9.  19.5]]


In [5]:
#addition
data+data

array([[ 3., -1.,  6.],
       [ 0., -6., 13.]])

In [6]:
#checking shape and datatype of numpy array
print("shape : \n",data.shape)

print("data type: \n ",data.dtype)


shape : 
 (2, 3)
data type: 
  float64


In [7]:
# conversion of list to numpy array

data1=[1,22,4,53,2,5]

arr1=np.array(data1)
arr1

array([ 1, 22,  4, 53,  2,  5])

In [8]:
#nested list to multidimensional array
data2=[[1,2,3,4,5],[6,7,8,9,0]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [9]:
#number of dimension of the ndarray
print(arr2.ndim)

print(arr2.shape)

2
(2, 5)


In [10]:
#creating array of zeros 
print(np.zeros(8))

print("multidimensional array consists of zeros :\n",np.zeros((3,6)))


[0. 0. 0. 0. 0. 0. 0. 0.]
multidimensional array consists of zeros :
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
# numpy.arange is an array-valued version of the built-in Python range function

np.arange(14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [12]:
#chacking datatype

arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [13]:
# You can explicitly convert or cast an array from one data type to another using ndarray’s astype method:
arr=np.arange(8)
print(arr,arr.dtype)

#changing datatype from int32 to float32


arr2=arr.astype(np.float32)
print("data type is change to float32 :\n",arr2,arr2.dtype)

[0 1 2 3 4 5 6 7] int32
data type is change to float32 :
 [0. 1. 2. 3. 4. 5. 6. 7.] float32


In [14]:
#convert flaot to int 

arr3=np.array((1.0,0.23,0.53,0.09))
arr3.dtype

arr4=arr3.astype(np.int32)
print("coverted to int32 from float64 : \n",arr4,arr4.dtype)


coverted to int32 from float64 : 
 [1 0 0 0] int32


In [15]:
#from string to flaot
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
string_to_float=numeric_strings.astype(float)
print(string_to_float,string_to_float.dtype)

[ 1.25 -9.6  42.  ] float64


In [16]:
# Arithmetic operation with NumPy Arrays
arr=np.array([[1,2,4,5,2],[2,4,5,2,7]])
arr


array([[1, 2, 4, 5, 2],
       [2, 4, 5, 2, 7]])

In [17]:
#addition
arr+arr

array([[ 2,  4,  8, 10,  4],
       [ 4,  8, 10,  4, 14]])

In [18]:
# multiplication
arr*arr

array([[ 1,  4, 16, 25,  4],
       [ 4, 16, 25,  4, 49]])

In [19]:
#  division
arr/arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# subtraction
arr-arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
arr**2


array([[ 1,  4, 16, 25,  4],
       [ 4, 16, 25,  4, 49]])

In [22]:
#comparision of the two array
arr2 = np.array([[0., 4., 1.,2.,4.], [7., 2., 12.,4.,3.]])
arr2>arr

array([[False,  True, False, False,  True],
       [ True, False,  True,  True, False]])

### Basic Indexing and Slicing

In [23]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#accessing  element at 5 index
arr[5]

5

In [25]:
#from 5 to 8 index
arr[5:8]

array([5, 6, 7])

In [26]:
#changing the element in array
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [27]:
# Now, when I change values in arr_slice, the mutations are reflected in the original
# array arr:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [28]:
arr_slice[1]=1234

arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [29]:
# The “bare” slice [:] will assign to all values in an array:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [30]:
#multidimentional array accessing

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [32]:
# third element of the first array

# arr2d[0][2]
arr2d[0,2]

3

In [33]:
# In multidimensional arrays, if you omit later indices, the returned object will be a
# lower dimensional ndarray consisting of all the data along the higher dimensions. So
# in the 2 × 2 × 3 array arr3d:

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)

arr3d[0]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr3d[0]=87
arr3d


array([[[87, 87, 87],
        [87, 87, 87]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
arr3d[1,0]



array([7, 8, 9])

### Indexing with slices
Like one-dimensional objects such as Python lists, ndarrays can be sliced with the
familiar syntax:


In [37]:
arr

array([87,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [38]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [42]:
# two dimentional array
print(arr2d)

print("slicing \n",arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
slicing 
 [[1 2 3]
 [4 5 6]]


In [43]:
# You can pass multiple slices just like you can pass multiple indexes

arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [44]:
arr2d[:, :1]


array([[1],
       [4],
       [7]])

Boolean Indexing

In [45]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [46]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [48]:
print(data.shape)
print(data.ndim)

(7, 2)
2


In [51]:
print(names=="Bob")  #return true where the bobs exists in the array

[ True False False  True False False False]


In [52]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [53]:
# Selects rows where names is "Bob" and all columns starting from the second.
data[names == "Bob", 1:]


array([[7],
       [0]])

In [55]:
# Selects all rows where names is not "Bob" using negation (~).
data[~(names == "Bob")]


array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [56]:
# Selects rows where names is either "Bob" or "Will".
mask = (names == "Bob") | (names == "Will")
data[mask]




array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [58]:
# Sets all negative values in data to 0.
data[data < 0] = 0
data


array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [59]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [63]:
print(arr)
print(arr[[4, 3, 0, 6]])

[87  1  2  3  4 64 64 64  8  9]
[ 4  3 87 64]


In [68]:
#taking transpose
arr_t=arr.T
arr_t

# nultiply with arr
arr_t*arr

array([7569,    1,    4,    9,   16, 4096, 4096, 4096,   64,   81])

In [69]:
arr

array([87,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [70]:
arr.swapaxes(0, 1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1

In [72]:
# Computes the square root of each element in arr.
np.sqrt(arr)



array([9.32737905, 1.        , 1.41421356, 1.73205081, 2.        ,
       8.        , 8.        , 8.        , 2.82842712, 3.        ])

In [73]:
# Computes the exponential of each element in arr.
np.exp(arr)


array([6.07603023e+37, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 6.23514908e+27, 6.23514908e+27, 6.23514908e+27,
       2.98095799e+03, 8.10308393e+03])

In [74]:
#maximum element
np.max(arr)

87

In [75]:
np.min(arr)   #minimum element

1

In [78]:
#sorting of array
np.sort(arr)

array([ 1,  2,  3,  4,  8,  9, 64, 64, 64, 87])