The NumPy ndarray provides a way to interpret a block of homogeneous data (either contiguous or strided) as a multidimensional array object. Here's a deeper dive into its internals:

Pointer to Data: Points to a block of data in RAM or a memory-mapped file.

Data Type (dtype): Describes the fixed-size value cells in the array.

Shape: A tuple indicating the array's shape.

Strides: A tuple of integers indicating the number of bytes to step to advance one element along a dimension.

In [4]:
import numpy as np

# np.ones((10, 5)) creates a 10x5 array filled with ones. 
# The shape attribute returns the dimensions of the array.

arr=np.ones((10, 5))
print(arr)
print(f"\nthe shape of the arr :\n {arr.shape}")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

the shape of the arr :
 (10, 5)


In [9]:
# The strides indicate the number of bytes to move to the next element in each dimension. 
# For a 3x4x5 array of float64 (8 bytes each), moving to the next element along the first dimension requires moving 160 bytes, the second 40 bytes, and the third 8 bytes.
arr = np.ones((6, 7, 5), dtype=np.float64)
print(arr.strides)

(280, 40, 8)


In [10]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 3 2 1]


#### Advanced Array Manipulation

In [12]:
# The reshape method changes the shape of the array to 4x2 without copying the data.
# ew shape should ne compatible with the original array's total number of elements.
arr = np.arange(8)
reshaped_arr = arr.reshape((4,2))
print(reshaped_arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [22]:
arr = np.arange(15)
reshaped_arr = arr.reshape((5,-1))
reshaped_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
# The ravel method flattens the array without copying the data if the values are contiguous.
#  This is useful for converting multi-dimensional arrays into one-dimensional arrays.

arr =np.arange(15).reshape((3,5))
print(arr)

print("flattens the array")
print(arr.ravel(),"\n")
print(f" 'F' order flattens it in column-major order :\n{arr.ravel("F")}")

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
flattens the array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

 'F' order flattens it in column-major order :
[ 0  5 10  1  6 11  2  7 12  3  8 13  4  9 14]


In [31]:
# np.concatenate joins arrays along the specified axis.
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

#  axis=0, arrays are stacked vertically
concat_arrs_vertically=np.concatenate([arr1, arr2], axis=0)
print(concat_arrs_vertically)

# axis=1, they are stacked horizontally
concat_arrs_horizentally=np.concatenate([arr1, arr2], axis=1)
print(concat_arrs_horizentally)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [36]:
# splitting arrays
arr = np.random.randn(5,2)
print(arr)

print("splitting array")
first, second, third = np.split(arr,[1,3])
print(" first ;", first)
print(" second ;",second)
print(" third ;", third)

[[ 0.30714036  0.28658946]
 [-0.25458272 -1.6415204 ]
 [-0.58291256 -0.56629653]
 [ 1.14222742  0.95812558]
 [-0.37051078 -0.59906708]]
splitting array
 first ; [[0.30714036 0.28658946]]
 second ; [[-0.25458272 -1.6415204 ]
 [-0.58291256 -0.56629653]]
 third ; [[ 1.14222742  0.95812558]
 [-0.37051078 -0.59906708]]


In [43]:
# Using r_ and c_
# np.r_ and np.c_ are used for stacking arrays along different axes.
# np.r_ is used for row-wise stacking (concatenation along axis 0).
# np.c_ is used for column-wise stacking (concatenation along axis 1).

arr = np.arange(6)
arr1 =arr.reshape((3,2))
arr2= np.random.randn(3,2)

print(f"\narr :\n {arr}\n arr1 :\n{arr1}\n arr2 \n {arr2}")

result_r=np.r_[arr1,arr2]

print(f'\nther result with np.r_  :\n {result_r}')


arr :
 [0 1 2 3 4 5]
 arr1 :
[[0 1]
 [2 3]
 [4 5]]
 arr2 
 [[-0.29235953 -0.45423389]
 [-0.52338193  0.6456812 ]
 [-0.07531655 -0.79403593]]

ther result with np.r_  :
 [[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [-0.29235953 -0.45423389]
 [-0.52338193  0.6456812 ]
 [-0.07531655 -0.79403593]]


In [44]:
# Column-wise stacking using c_
result_c = np.c_[np.r_[arr1, arr2], arr]
print(result_c)

[[ 0.          1.          0.        ]
 [ 2.          3.          1.        ]
 [ 4.          5.          2.        ]
 [-0.29235953 -0.45423389  3.        ]
 [-0.52338193  0.6456812   4.        ]
 [-0.07531655 -0.79403593  5.        ]]


In [50]:
# Repeating Elements: tile and repeat
# np.repeat repeats elements of an array along a specified axis.
# np.tile repeats the whole array a specified number of times along each axis.

arr = np.arange(3)

print(arr)
# repeating element 3 times

repeated_arr = arr.repeat(3)
print(f"repeated array",repeated_arr)

[0 1 2]
repeated array [0 0 1 1 2 2]


In [51]:
repeated_arr = arr.repeat(4)
print(f"repeated array",repeated_arr)

repeated array [0 0 0 0 1 1 1 1 2 2 2 2]


In [54]:
# np.tile repeats the whole array a specified number of times along each axis.
arr = np.random.randn(2,2)
print(arr)

tiled_arr = np.tile(arr,(2,2))
print("tile array: \n",tiled_arr)

[[-0.64906792 -0.32531048]
 [-0.1882524  -0.34755762]]
tile array: 
 [[-0.64906792 -0.32531048 -0.64906792 -0.32531048]
 [-0.1882524  -0.34755762 -0.1882524  -0.34755762]
 [-0.64906792 -0.32531048 -0.64906792 -0.32531048]
 [-0.1882524  -0.34755762 -0.1882524  -0.34755762]]


#### Sorting in NumPy


In [60]:
# In-place Sorting with sort Method
arr = np.random.randn(6)
arr.sort()
print(arr)



[-1.27404218 -0.78190183  0.04427731  0.40604914  1.25997573  1.39120603]


In [61]:
arr = np.random.randn(3, 5)
arr

array([[ 0.190402  ,  0.69843576,  1.29236703, -0.38477051, -0.47045283],
       [-2.35806284,  0.64992132, -0.20709206, -1.12028215,  0.45777332],
       [-1.11004425,  0.57904166, -0.44935723,  0.69053085, -0.16865323]])

In [65]:
arr[:,0].sort() # Sort first column values in-place
print(arr)

[[-2.35806284  0.69843576  1.29236703 -0.38477051 -0.47045283]
 [-1.11004425  0.64992132 -0.20709206 -1.12028215  0.45777332]
 [ 0.190402    0.57904166 -0.44935723  0.69053085 -0.16865323]]


In [67]:
arr = np.random.randn(5)
print(arr)

sorted_arr = np.sort(arr)
print(sorted_arr)
print(arr)

[ 0.50174523  1.18946539  0.97111576 -1.00960813  0.50105687]
[-1.00960813  0.50105687  0.50174523  0.97111576  1.18946539]
[ 0.50174523  1.18946539  0.97111576 -1.00960813  0.50105687]
